# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:

---
include:
    # Corne Wireless
  - board: nice_nano_v2
    shield: acorn_central_dongle
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: acorn_peripheral_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: acorn_central_left
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: acorn_peripheral_right
    snippet: studio-rpc-usb-uart
